### ISSUE TITLE
Support language Arabia

### ISSUE THREAD

**Issue by iturki92** [UsrLightmann/StripeCount#2]
Don’t work with languag Arabia
![image](https://user-images.githubusercontent.com/41507876/85945600-a5945600-b947-11ea-94a3-ce31f1aad4d9.png)
![image](https://user-images.githubusercontent.com/41507876/85945604-a927dd00-b947-11ea-9e27-f17a4808627a.png)

**Comment by L1ghtmann** [comment]
Hey,

Thanks for letting me know. I will add RTL support in the next update.

**Comment by iturki92** [comment]
Thank you.
