### ISSUE TITLE
Display Problem

### ISSUE THREAD

**Issue by Potterd** [UsrLightmann/StripeCount#5]
Sometimes works and sometimes looks like the attached screenshot - force close Zebra and reopen seems to fix
![687296F9-17CE-4F9A-88AA-4F2FDD304DBA](https://user-images.githubusercontent.com/2848810/117361899-73a92580-ae6f-11eb-9f01-31013878899e.png)

**Comment by Potterd** [comment]
Last occurrence - force close Zebra and reopen did not fix, reinstall StripeCount to fix

**Comment by Potterd** [comment]
Sorry, didn’t mean to close

**Comment by Potterd** [comment]
Lately, reinstall Zebra to fix - there is no reliable workaround to fix this, all of the steps mentioned can work or not work to return the display to normal

**Comment by L1ghtmann** [comment]
What version of StripeCount are you using? The reason I'm asking is because this width issue was addressed back in v1.0.3.1. 

Also, what device, iOS version, and Zebra version?

**Comment by Potterd** [comment]
Thanks for getting back to me !

 

StripeCount v1.0.3.2.2

iPhone 8

iOS 14.3

Zebra v1.1.18

 

Also was able to reproduce with Zebra v1.1.17

 

Let me know if you need anything additional.

 

Regards,

 

David Potter

DPotter Consulting Inc

(415) 485-5876 (office)

(415) 608-7797 (mobile)

 ***@***.***> ***@***.***

 

You can view me on LinkedIn:  <http://www.linkedin.com/in/dpotterconsulting> www.linkedin.com/in/dpotterconsulting

**Comment by Potterd** [comment]
Hope you are still looking at this / Plz let me know if you need anything additional / help with testing .....

**Comment by Potterd** [comment]
2nd device iPhone SE either the same issue: 
![574EBBFE-387E-4021-A1ED-0713F28E318A](https://user-images.githubusercontent.com/2848810/118430721-3856f400-b6c4-11eb-9bd0-961248af733b.png)

**Comment by Potterd** [comment]
2nd device with the same issue .....

**Comment by Potterd** [comment]
Any update ?
Have you been able to reproduce this issue or should I be testing for a tweak conflict.

**Comment by L1ghtmann** [comment]
I have not been able to replicate this, no. Could you shoot me an email (lightmanns11@gmail.com)?

**Comment by Potterd** [comment]
Hope you received my earlier messages .....

David Potter
DPotter Consulting Inc
(415) 485-5876 (office)
(415) 608-7797 (mobile)
***@***.***

You can view me on LinkedIn: www.linkedin.com/in/dpotterconsulting

**Comment by UsrLightmann** [comment]
Hey, any word on the build I sent over? I still have a couple ideas I could try out if the issue isn't resolved.

**Comment by L1ghtmann** [comment]
Thanks again for your help testing! 

Fixed in v1.0.3.3.
